# Generated by Django 4.1.7 on 2023-04-01 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0003_bidmodel_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bidmodel",
            name="bid_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
