# Generated by Django 4.1.7 on 2023-04-03 17:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0012_alter_bidmodel_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockChainModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("block", models.UUIDField()),
                ("time_stamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("type_of_block", models.CharField(max_length=200)),
                ("block_detail", models.CharField(max_length=200)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="apiApp.productmodel",
                    ),
                ),
            ],
        ),
    ]
