# Generated by Django 4.1.7 on 2023-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiApp", "0013_blockchainmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blockchainmodel",
            name="block",
            field=models.CharField(max_length=128),
        ),
    ]
