# Generated by Django 4.1.7 on 2023-11-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("apiApp", "0015_alter_productmodel_p_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bidmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bidmodel",
            unique_together={("product", "price")},
        ),
    ]
